### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by mikestumbo** [eddiehoyle/screenspace#13]
Hey Eddie, I’m an Animation Generalist w/ an emphasis in rigging & TD. But I’m a rookie in scripting. Is it  possible of getting a build of your Screenspace plugin w/o CMake and git? I’ve been trying to make it for Maya2023.1 on OSX for over a week but to no avail.

**Comment by eddiehoyle** [comment]
Hey Mike, sorry, I just noticed this message now. Are you still interested in a Maya 2023 build for Mac OS?
